# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'REroot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReRoot

  pod 'SideMenu'
  pod 'ReachabilitySwift'
  pod 'Alamofire','~> 5.0.0'
  pod 'PKHUD', '~> 5.0'
  pod 'DLRadioButton'
  pod 'KeychainAccess'
  pod 'IQKeyboardManagerSwift'
#  pod 'SDWebImage', '~> 4.4.2'
  pod 'SDWebImage', '~> 5.8'
  pod 'JJFloatingActionButton'
  pod 'FloatingPanel'
#  pod 'FittedSheets'
#  pod 'DropDown', '~> 2.3.4'
  pod 'Siren'
#  pod 'Fabric'
#  pod 'Firebase/Analytics'
#  pod 'Firebase/Crashlytics'
  pod 'FirebaseCrashlytics', '~> 8.11'

# Add the pod for Firebase Crashlytics
#pod 'Firebase/Crashlytics'

# Recommended: Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
#  pod 'AWSS3', '~> 2.9.7'
  pod 'AWSS3'

  target 'ReRootTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReRootUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
